server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

# POSTGRESQL SETTINGS
spring:
  datasource:
    url: jdbc:postgresql://ec2-34-242-84-130.eu-west-1.compute.amazonaws.com:5432/dat0vaps280lhe
    username: bvqowqruocembd
    password: 31d4589d4a731d9c65a2e34be69b48fcf956520eaf50d7921e54a6ef334a69b1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true

# ORACLE SETTINGS
# spring:
#   datasource:
#     url: jdbc:oracle:thin:@localhost:1521/contactlist_db
#     username: contactlist_user
#     password: 12345
#     driver-class-name: oracle.jdbc.OracleDriver
#   jpa:
#     show-sql: true
#     database-platform: org.hibernate.dialect.Oracle12cDialect
#     hibernate:
#       ddl-auto: update
#     properties:
#       format-sql: true

contactlist:
  app:
    jwtSecret: contact@List@372
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/contactlist.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.citylist]': INFO

info:
  application:
    name: 'Contact List Backend Application'
    description: 'This is Contact List Backend App developed by Feridun OZCELIK'
    version: '@project.version@'

